service: cognito-example

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    AUTHSIGNAL_SECRET: ${env:AUTHSIGNAL_SECRET}
    AUTHSIGNAL_URL: ${env:AUTHSIGNAL_URL}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    USER_POOL_ID: ${env:USER_POOL_ID}
  httpApi:
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.authorization
        issuerUrl: https://cognito-idp.${env:AWS_REGION}.amazonaws.com/${env:USER_POOL_ID}
        audience:
          - ${env:USER_POOL_CLIENT_ID}

package:
  individually: true

functions:
  defineAuthChallenge:
    handler: triggers/define-auth-challenge.handler

  createAuthChallenge:
    handler: triggers/create-auth-challenge.handler

  verifyAuthChallengeResponse:
    handler: triggers/verify-auth-challenge-response.handler

  init-sms-challenge:
    handler: api/init-sms-challenge.handler
    events:
      - httpApi:
          method: post
          path: /challenge/sms

  verify-sms-challenge:
    handler: api/verify-sms-challenge.handler
    events:
      - httpApi:
          method: post
          path: /verify/sms

  init-social-auth:
    handler: api/init-social-auth.handler
    events:
      - httpApi:
          method: post
          path: /init-social-auth

  addPasskey:
    handler: api/add-passkey.handler
    events:
      - httpApi:
          method: post
          path: /authenticators/passkey
          authorizer:
            name: jwtAuthorizer

build:
  esbuild:
    bundle: true
    external:
      - "@aws-sdk/client-cognito-identity-provider"
