service: cognito-example

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    AUTHSIGNAL_SECRET: ${env:AUTHSIGNAL_SECRET}
    AUTHSIGNAL_URL: ${env:AUTHSIGNAL_URL}
    USER_POOL_ID: ${env:USER_POOL_ID}
  httpApi:
    cors: true
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.authorization
        issuerUrl: https://cognito-idp.${env:AWS_REGION}.amazonaws.com/${env:USER_POOL_ID}
        audience:
          - ${env:USER_POOL_WEB_CLIENT_ID}

package:
  individually: true

functions:
  defineAuthChallenge:
    handler: triggers/define-auth-challenge.handler

  createAuthChallenge:
    handler: triggers/create-auth-challenge.handler

  verifyAuthChallengeResponse:
    handler: triggers/verify-auth-challenge-response.handler

  preSignUp:
    handler: triggers/pre-sign-up.handler

  addAuthenticator:
    handler: api/add-authenticator.handler
    events:
      - httpApi:
          method: post
          path: /authenticators
          authorizer:
            name: jwtAuthorizer
