service: cognito-example

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    AUTHSIGNAL_SECRET: ${env:AUTHSIGNAL_SECRET}
    AUTHSIGNAL_URL: ${env:AUTHSIGNAL_URL}
  httpApi:
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.authorization
        issuerUrl: ${env:JWT_AUTHORIZER_ISSUER_URL}
        audience:
          - ${env:JWT_AUTHORIZER_AUDIENCE}

package:
  individually: true

functions:
  defineAuthChallenge:
    handler: define-auth-challenge.handler

  createAuthChallenge:
    handler: create-auth-challenge.handler

  verifyAuthChallengeResponse:
    handler: verify-auth-challenge-response.handler

  preSignUp:
    handler: pre-sign-up.handler

  addAuthenticator:
    handler: add-authenticator.handler
    events:
      - httpApi:
          method: post
          path: /authenticators
          authorizer:
            name: jwtAuthorizer
